version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: always

  backend:
    image: liljoker/backend:v1
    container_name: backend
    expose:
      - '5000' # expose pour NGINX, pas besoin de port externe
    env_file:
      - .env.backend
    depends_on:
      - mongo
    networks:
      - app-network
    restart: always

  front:
    image: liljoker/frontend:v1
    container_name: frontend
    expose:
      - '5173' # expose pour NGINX
    env_file:
      - .env.front
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - backend
    networks:
      - app-network
    restart: always

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
